//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewLottoApp2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lottoHistory
    {
        public System.DateTime Date { get; set; }
        public string Mid_Day { get; set; }
        public string Pk1 { get; set; }
        public string Pk2 { get; set; }
        public string Pk3 { get; set; }
    }
}
